-- Ballarat seed businesses
INSERT INTO businesses (id, slug, name, type, section, suburb, location, description, city, status, emoji, approved)
VALUES
  (
    'lespresso-ballarat',
    'lespresso-ballarat-central',
    'L''Espresso',
    'Café',
    'eat',
    'Ballarat Central',
    '417 Sturt St, Ballarat Central',
    '<strong>One of Ballarat''s most iconic cafes — a local institution on Sturt Street.</strong><br><br>Known for strong coffee and a relaxed European-style atmosphere, L''Espresso has drawn loyal regulars for decades. The kind of place that anchors a street and defines a city''s café culture.',
    'ballarat',
    'approved',
    '☕',
    true
  ),
  (
    'eureka-bistro-ballarat',
    'eureka-bistro-ballarat-central',
    'Eureka Bistro',
    'Restaurant',
    'eat',
    'Ballarat Central',
    '314-316 Sturt St, Ballarat Central',
    '<strong>A Ballarat institution — Italian dining done with warmth and longevity.</strong><br><br>Close to 50 years of handmade pasta, wood-fired pizza and house-made desserts in a rustic, welcoming setting on Sturt Street. The kind of restaurant that earns its place in a city''s history.',
    'ballarat',
    'approved',
    '🍝',
    true
  ),
  (
    'forge-pizzeria-ballarat',
    'forge-pizzeria-ballarat-central',
    'The Forge Pizzeria',
    'Restaurant',
    'eat',
    'Ballarat Central',
    '14 Armstrong St North, Ballarat Central',
    '<strong>Authentic woodfired pizza in a heritage Armstrong Street building.</strong><br><br>A popular spot well-regarded for its Italian-style pizzas and convivial atmosphere. The heritage fit-out adds character that matches the food.',
    'ballarat',
    'approved',
    '🍕',
    true
  ),
  (
    'hop-temple-ballarat',
    'hop-temple-ballarat-central',
    'Hop Temple',
    'Bar',
    'drink',
    'Ballarat Central',
    '24-30 Armstrong St North, Ballarat Central',
    '<strong>Ballarat''s craft beer mecca — reputedly the largest range of craft beer in Victoria.</strong><br><br>Over 200 craft beers and ciders tucked down a laneway off Armstrong Street. Casual food, excellent taps, and the kind of bar that serious beer drinkers make a point of visiting.',
    'ballarat',
    'approved',
    '🍺',
    true
  ),
  (
    'fika-coffee-ballarat',
    'fika-coffee-brewers-ballarat-central',
    'FIKA Coffee Brewers',
    'Café',
    'eat',
    'Ballarat Central',
    '36A Doveton St North, Ballarat Central',
    '<strong>Specialty coffee with a Scandinavian ethos on Doveton Street.</strong><br><br>Single-origin brews, a considered fit-out, and a genuine focus on quality. Popular with the local coffee community and anyone who takes their morning cup seriously.',
    'ballarat',
    'approved',
    '☕',
    true
  ),
  (
    'cafe-lekker-ballarat',
    'cafe-lekker-ballarat-central',
    'Cafe Lekker',
    'Café',
    'eat',
    'Ballarat Central',
    '11 Doveton St North, Ballarat Central',
    '<strong>A well-loved neighbourhood café with a strong local following.</strong><br><br>Consistently good coffee and wholesome all-day breakfast and brunch options. The kind of reliable local you''d visit every weekend without thinking twice.',
    'ballarat',
    'approved',
    '🥞',
    true
  ),
  (
    'moon-and-mountain-ballarat',
    'moon-and-mountain-ballarat-central',
    'Moon & Mountain',
    'Restaurant',
    'eat',
    'Ballarat Central',
    '220 Mair St, Ballarat Central',
    '<strong>One of Ballarat''s most talked-about contemporary restaurants.</strong><br><br>Modern Asian eatery inspired by the hawker dining bars of South East Asia — bold shared plates, communal dining, and flavours that have made it a genuine destination for food lovers in the region.',
    'ballarat',
    'approved',
    '🌏',
    true
  ),
  (
    'boatshed-restaurant-ballarat',
    'boatshed-restaurant-lake-wendouree',
    'Boatshed Restaurant',
    'Restaurant',
    'eat',
    'Lake Wendouree',
    '27A Lake Wendouree Foreshore, Ballarat',
    '<strong>A scenic waterfront restaurant on the shores of Lake Wendouree.</strong><br><br>Modern Australian cuisine in a landmark lakeside setting — a natural choice for special occasions. The view alone makes it worth the visit, and the food backs it up.',
    'ballarat',
    'approved',
    '🛶',
    true
  ),
  (
    'underbar-ballarat',
    'underbar-ballarat-central',
    'Underbar',
    'Restaurant',
    'eat',
    'Ballarat Central',
    '3 Doveton St North, Ballarat Central',
    '<strong>Ballarat''s most intimate fine dining experience — awarded a hat in The Age Good Food Guide 2026.</strong><br><br>A 20-seat chef-led degustation restaurant open Friday and Saturday evenings. Seasonal tasting menu with a strong focus on foraged and local produce. Book well ahead.',
    'ballarat',
    'approved',
    '⭐',
    true
  ),
  (
    'babae-ballarat',
    'babae-ballarat-central',
    'Babae',
    'Restaurant',
    'eat',
    'Ballarat Central',
    '710 Sturt St, Ballarat Central',
    '<strong>One-hat fine dining championing Goldfields produce at Hotel Vera.</strong><br><br>A 26-seat hatted restaurant with its own kitchen farm, serving a seven-course degustation dinner and four-course lunch. Awarded a chef''s hat since 2025 and one of regional Victoria''s most acclaimed dining destinations.',
    'ballarat',
    'approved',
    '🌟',
    true
  );
